# Generated by Django 6.0 on 2026-07-10 11:47

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtistrySettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "spawn_art_channel",
                    models.TextField(
                        blank=True,
                        help_text="The forum channel ID that will manage spawn artwork.",
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^\\d{17,21}$"), message="Invalid forum channel ID."
                            )
                        ],
                    ),
                ),
                (
                    "card_art_channel",
                    models.TextField(
                        blank=True,
                        help_text="The forum channel ID that will manage card artwork.",
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^\\d{17,21}$"), message="Invalid forum channel ID."
                            )
                        ],
                    ),
                ),
                (
                    "accepted_message",
                    models.TextField(
                        blank=True,
                        default="Hi {user}, your artwork for **{ball}** has been accepted!",
                        help_text=(
                            "The message that will be sent to a user through DMs when their art is accepted. "
                            "If blank, no message will be sent."
                        ),
                        max_length=256,
                    ),
                ),
                (
                    "accepted_emoji",
                    models.CharField(
                        blank=True,
                        default="✅",
                        help_text="A unicode character that will be reacted with. If blank, no reaction will be added.",
                        max_length=20,
                    ),
                ),
                (
                    "safe_thread_ids",
                    models.TextField(
                        blank=True,
                        help_text="Semicolon-delimited thread IDs that will not be deleted during generation.",
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^(\\d{17,21}(;\\d{17,21})*)?$"),
                                message="The IDs must be semicolon-separated",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Settings",
                "permissions": [
                    ("can_generate", "Can generate art threads."),
                    ("can_accept", "Can accept art submissions."),
                ],
            },
        )
    ]
