# Generated by Django 6.0 on 2026-07-11 14:51

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistrysettings',
            name='emoji_art_channel',
            field=models.TextField(blank=True, help_text='The forum channel ID that will manage emoji artwork.', validators=[django.core.validators.RegexValidator(re.compile('^\\d{17,21}$'), message='Invalid forum channel ID.')]),
        ),
    ]
