# Generated by Django 6.0 on 2026-07-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("artistry", "0002_artistrysettings_emoji_art_channel")]

    operations = [
        migrations.AlterField(
            model_name="artistrysettings",
            name="accepted_message",
            field=models.TextField(
                blank=True,
                default="Hi {user}, your artwork for **{ball}** has been accepted!",
                help_text=(
                    "The message that will be sent to a user through DMs when their art is accepted. "
                    "If blank, no message will be sent."
                ),
                max_length=2000,
            ),
        )
    ]
